language: android

before_install:
 - chmod +x gradlew
 - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
 - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
 - echo yes | android update sdk --filter android-18 --no-ui --force > /dev/null
 - echo yes | android update sdk --filter android-19 --no-ui --force > /dev/null
 - echo yes | android update sdk --filter sysimg-18 --no-ui --force > /dev/null
 - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
 - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
 - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-19.0.1

    # The SDK version used to compile your project
    - android-20

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19